name: Run Tests

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']
      
    paths: 
      - '**'

env:
  DOTNET_SDK_VERSION: 8.0
  SOLUTION_PATH: "BrowseRouter.sln"

jobs:

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        # ./ is the repo root
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Build
        run: dotnet build --configuration Release

      - name: Run dotnet test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --results-directory test-results --logger "trx;LogFilePrefix=TestResults"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.trx
