name: Build for Windows
on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']
    paths: 
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    name: Build on self-hosted
    runs-on: m2mini-win11
    permissions:
      contents: write
    defaults:
      run:
        # ./ is the repo root
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Get version
        run: |
          $version=$(pwsh ./Get-ProjectVersion.ps1 -ProjectPath BrowseRouter)
          echo "Version is: $version"
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Show version
        run: |
          echo "Version is: ${{ env.VERSION }}"
      - name: Build and sign
        run: pwsh ./make.ps1
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./Releases/**/*.zip"
          draft: true
          allowUpdates: true
          tag: ${{ env.VERSION }}
