name: Build for Windows
on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']
    paths: 
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    name: Build on self-hosted
    runs-on: m2mini-win11
    permissions:
      contents: write
    defaults:
      run:
        # ./ is the repo root
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Get version
        run: |
          $version = ./Get-ProjectVersion.ps1 -ProjectPath BrowseRouter
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Get PR URL
        run: |
          $pr = ${{ github.event.pull_request.number }}
          $url = "https://github.com/nref/BrowseRouter/pull/$pr"
          echo "PR_URL=$url" >> $env:GITHUB_ENV

      - name: Get PR Title
          run: |
            $title=$(gh pr view $env:PR_URL --json title -q .title)
            echo "PR_TITLE=$title" >> $GITHUB_ENV
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR Description
          run: |
            $description=$(gh pr view $env:PR_URL --json body -q .body)
            echo "PR_DESCRIPTION=$description" >> $GITHUB_ENV
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and sign
        run: pwsh ./make.ps1

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./Releases/**/*.zip"
          draft: true
          allowUpdates: true
          tag: $env:VERSION
          name: "$env:VERSION - $env:PR_TITLE"
          body: $env:PR_DESCRIPTION
